
language: node_js
node_js:
  - '10'
  - '8'
before_install:
  - npm i -g npm@latest
install:
  - npm install
development:
  - npm start
production:
  - npm run build
cache:
  directories:
    - node_modules
